In [3]:
import numpy as np

## reshape

In [3]:
test_matrix = [[1,2,3,4],
              [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [5]:
np.array(test_matrix).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [6]:
np.array(test_matrix).reshape(2,-1,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [7]:
np.array(test_matrix).reshape(8)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [8]:
np.array(test_matrix).reshape(2,-1)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

## flatten() or flat

In [13]:
test_matrix = [[[1,2,3,4], [1,2,5,8]],
              [[1,2,3,4], [1,2,5,8]]]
test_matrix = np.array(test_matrix)
test_matrix.shape

(2, 2, 4)

In [11]:
test_matrix.flatten().size

16

In [12]:
test_matrix.flatten().shape

(16,)

## indexing

In [17]:
test_example = [[1,2,3],[4,5,6]]
test_example = np.array(test_example)

In [19]:
test_example[0,0]

1

In [20]:
test_example[0][0]

1

In [21]:
test_example[0,0] = 10
test_example

array([[10,  2,  3],
       [ 4,  5,  6]])

In [22]:
test_example[1,2] = 5
test_example

array([[10,  2,  3],
       [ 4,  5,  5]])

## slicing

In [4]:
test_example = np.array([[1,2,3,4,5],[4,5,6,7,8]], int)
test_example

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [5]:
test_example[:,2:]

array([[3, 4, 5],
       [6, 7, 8]])

In [6]:
test_example[1,1:3]

array([5, 6])

In [8]:
test_example[1,1:3].shape

(2,)

In [10]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [11]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [12]:
a[:, ::2]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

## arrange

In [13]:
list(range(0,10,3))

[0, 3, 6, 9]

In [15]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [16]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## ones, zeros and empty

In [17]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.empty(shape=(10,), dtype = np.int8) #shape은 항상 tuple값
# 메모리만 잡는 것이기 때문에 남아있는 값들이 출력. 출력할 때마다 값이 바뀜

array([  0, -73, -50, -72, -85,   1,   0,   0,   0,   0], dtype=int8)

## something_like

In [23]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix) #zeros_like, empty_like도 가능

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## identity

In [26]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

## eye

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(3,5,k=2) #k로 시작 열 정함

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.eye(3,5,dtype =np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

## diag

In [31]:
matrix = np.arange(12).reshape(3,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
np.diag(matrix, k=2)

array([2, 7])

In [33]:
np.diag(matrix, k=1)

array([ 1,  6, 11])

In [34]:
np.diag(matrix, k=-1)

array([4, 9])

In [35]:
np.diag(matrix)

array([ 0,  5, 10])

## random sampling

In [36]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.47073377,  1.36539016, -0.4576948 , -0.71472758, -0.65682083],
       [-1.47756287, -0.87203688,  1.21629198,  0.11139119, -0.75411793]])

In [37]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.56281811, 0.30381486, 0.77925157, 0.18263783, 0.20797513],
       [0.54389199, 0.43805714, 0.04416317, 0.09927452, 0.45702949]])

## operation functinos

In [39]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
test_array.sum(dtype=np.float)

<ipython-input-41-5c571f18da20>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_array.sum(dtype=np.float)


55.0

In [42]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
test_array.sum(axis=1),test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [49]:
third_order_tensor = np.arange(1,37).reshape(3,3,4)
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [50]:
third_order_tensor.sum(axis=2)

array([[ 10,  26,  42],
       [ 58,  74,  90],
       [106, 122, 138]])

In [51]:
third_order_tensor.sum(axis=0), third_order_tensor.sum(axis=1)

(array([[39, 42, 45, 48],
        [51, 54, 57, 60],
        [63, 66, 69, 72]]),
 array([[15, 18, 21, 24],
        [51, 54, 57, 60],
        [87, 90, 93, 96]]))

## mean & std

In [55]:
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [53]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

In [54]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

## concatenate

In [60]:
a = np.array([[1,2,3]])
b = np.array([[1,2,4]])
np.vstack((a,b)), np.concatenate((a,b), axis=0)

(array([[1, 2, 3],
        [1, 2, 4]]),
 array([[1, 2, 3],
        [1, 2, 4]]))

In [58]:
a = np.array([[1],[2],[3]])
b = np.array([[1],[2],[4]])
np.hstack((a,b))

array([[1, 1],
       [2, 2],
       [3, 4]])

In [62]:
a = np.array([[1,2],[3, 4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1) #T: transpose

array([[1, 2, 5],
       [3, 4, 6]])

## any operators

#### operations b/t arrays

In [64]:
test_a = np.array([[1,2,3],[4,5,6]], float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [65]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [66]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

#### element-wise operations

In [68]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

#### dot product

In [69]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(1,7).reshape(3,2)

test_a, test_b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [70]:
test_a.dot(test_b)

array([[22, 28],
       [49, 64]])

#### transpose

In [71]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

#### broadcasting

In [79]:
test_a = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

test_a, scalar

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 3)

In [75]:
test_a + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [76]:
test_a - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [77]:
test_a * scalar

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [78]:
test_a / scalar

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [80]:
test_a // 0.2

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [81]:
test_a ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [83]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)

test_matrix, test_vector

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([10, 20, 30]))

In [84]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

### numpy performance

In [87]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar*value)
        
iteration_max = 100000000

vector = list(range(iteration_max))
scalar = 2

%timeit scalar_vector_product(scalar, vector) # for loop
%timeit [scalar*value for value in range(iteration_max)]  # list

%timeit np.arange(iteration_max)*scalar  # numpy

KeyboardInterrupt: 

### comparison

In [88]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.any(a>5), np.any(a<0)

(True, False)

In [90]:
np.all(a>5), np.all(a<0)

(False, False)

In [91]:
test_a = np.array([1,3,0],float)
test_b = np.array([5,2,1],float)
test_a > test_b

array([False,  True, False])

In [92]:
test_a == test_b

array([False, False, False])

In [93]:
(test_a > test_b).any()

True

In [100]:
a = np.array([1,3,0], float)
np.logical_and(a>0, a<3)  # and 조건의 condition

array([ True, False, False])

In [96]:
b = np.array([True, False, True], bool)
np.logical_not(b)  # not 조건의 condition

array([False,  True, False])

In [98]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)  # or 조건의 condition

array([ True,  True,  True])

#### np.where

In [101]:
np.where(a>0, 3, 2)

array([3, 3, 2])

In [102]:
a = np.arange(10)
np.where(a>5)

(array([6, 7, 8, 9], dtype=int64),)

In [103]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [104]:
np.isfinite(a)

array([ True, False, False])

#### argmax & argmin

In [105]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [106]:
a = np.array([[1,2,4,7],[5,8,78,6],[23,3,78,2]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 2, 2], dtype=int64), array([0, 0, 0, 2], dtype=int64))

#### boolean & fancy indexing

In [109]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [110]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [111]:
condition = test_array <3
test_array[condition]

array([1., 0., 2.])

In [112]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int) # 원소값이 a의 index 안에 속해야 함
a[b]

array([2., 2., 4., 8., 6., 4.])

In [114]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [115]:
a = np.array([[1,4],[9,16]], float)
b = np.array([0,0,1,1,0], int) # 원소값이 a의 index 안에 속해야 함
c = np.array([0,1,1,1,1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

### data i/o

In [116]:
a_int = np.array([1,2,3,4,1,23,53,46], float)

In [117]:
a_int = a_int.astype(int)

In [118]:
np.save("npy_test", arr=a_int)

In [120]:
a_test = np.load(file = "npy_test.npy")
a_test

array([ 1,  2,  3,  4,  1, 23, 53, 46])