In [3]:
x = [1,7,2]
x

[1, 7, 2]

In [4]:
import numpy as np

x = np.array([1,7,2])
x

array([1, 7, 2])

In [5]:
y = np.array([5,2,1])

In [6]:
x+y

array([6, 9, 3])

In [7]:
x-y

array([-4,  5,  1])

In [8]:
x*y

array([ 5, 14,  2])

In [13]:
def l1_norm(x):
    x_norm = np.abs(x)
    x_norm = np.sum(x_norm)
    return x_norm

def l2_norm(x):
    x_norm = x*x
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

In [11]:
l1_norm(x)

10

In [14]:
l2_norm(x)

7.3484692283495345