In [9]:
import numpy as np

X = np.array([[1,-2,3],
             [7,5,0],
             [-2,-1,2]])

In [10]:
Y = np.array([[0,1],
            [1,-1],
            [-2,1]])

In [11]:
X@Y

array([[-8,  6],
       [ 5,  2],
       [-5,  1]])

In [12]:
np.transpose(X)

array([[ 1,  7, -2],
       [-2,  5, -1],
       [ 3,  0,  2]])

In [13]:
Y = np.array([[0,1,-1],
            [1,-1,0]])

In [14]:
np.inner(X,Y)

array([[-5,  3],
       [ 5,  2],
       [-3, -1]])

In [17]:
# 역행렬
X_inv = np.linalg.inv(X)
X_inv

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [18]:
X@X_inv

array([[ 1.00000000e+00, -1.38777878e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -5.55111512e-17],
       [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

In [20]:
#유사역행렬
Y_inv = np.linalg.pinv(Y)
Y_inv

array([[ 0.33333333,  0.66666667],
       [ 0.33333333, -0.33333333],
       [-0.66666667, -0.33333333]])

In [22]:
#n<m이니까 YY+
Y@Y_inv

array([[ 1.00000000e+00, -4.44089210e-16],
       [ 1.66533454e-16,  1.00000000e+00]])

In [23]:
# 회귀분석 결과와 Moore-Penrose 역행렬 값 비교
from sklearn.linear_model import LinearRegression

X = np.array([[0,1],
            [1,-1],
            [-2,1]])
y = [1,2,3]

x_test = np.array([[2,-1],
            [0,5],
            [1,-1]])

model = LinearRegression()
model.fit(X, y)
y_test = model.predict(x_test)
y_test

array([ 1., -3.,  2.])

In [27]:
#intercept를 추가해야 회귀 분석과 동일한 결과 도출됨

X_ = np.array([np.append(x,[1]) for x in X]) # y절편(intercept) 항 추가
beta = np.linalg.pinv(X_)@y
x = np.array([np.append(x,[1]) for x in x_test])
y_test = x @ beta
y_test

array([ 1., -3.,  2.])